name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker warehouse.api
      run: docker build -t georgiatech/tamaspalya/warehouseapi:latest ./Warehouse.API

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERPW }}

    - name: Push Docker warehouse.api
      run: docker push georgiatech/tamaspalya/warehouseapi:latest
